Add state consistency (with new meta)
gear-dapps/dutch-auction pull request #45
Opened 2023-01-27 00:59 UTC by azoyan

2023-01-31 16:15 UTC, shamilsan approved these changes

2023-01-31 16:15 UTC, shamilsan commented on src/contract.rs
> +        }
I'd use `map_err` here to avoid `if let` with long condition.
```suggestion
        .map_err(|e| {
            gstd::debug!("{:?}", e);
            Error::NftTransferFailed
        })?;
```

2023-01-31 16:15 UTC, shamilsan commented on src/contract.rs
> +                "Failed to encode or reply with `Result<NFTPixelboardEvent, NFTPixelboardError>`",
`NFTPixelboard`?

2023-02-02 18:11 UTC, LouiseMedova requested changes

2023-02-02 18:11 UTC, LouiseMedova commented on src/contract.rs
> +        .unwrap()
Replace with `expect`

2023-02-02 18:11 UTC, LouiseMedova commented on src/contract.rs
> +        .unwrap()
Replace with `expect`

2023-02-02 18:11 UTC, LouiseMedova commented on src/contract.rs
> +        if let Err(e) = msg::send(self.nft.owner, "REWARD", price) {
What if NFT is transferred and the gas ran out here?
The value is already on the contract
And the buyer may not continue the transaction after receiving the NFT

2023-03-03 11:54 UTC, LouiseMedova approved these changes

2023-03-03 12:39 UTC, merged